services:
    rabbitmq:
        image: rabbitmq:4-management
        container_name: rabbitmq-service
        ports:
            - "5672:5672"
            - "15672:15672"
        restart: unless-stopped
        environment:
            - RABBITMQ_DEFAULT_USER=rmq
            - RABBITMQ_DEFAULT_PASS=rmq
